name: 'PR Size Checker'
description: 'Check the size of a pull request and comment if it is too large.'
author: 'ouchi2501'

# Define your inputs here.
inputs:
  github-token:
    description: 'Derivative token for using the GitHub REST API'
    required: true
  max-lines:
    description: 'The maximum number of lines to output'
    required: true

runs:
  using: node20
  main: dist/index.js
